export default {
  ENTRY_FORMAT_URL: 'http://hl7.org/fhir/StructureDefinition/entryFormat',
  STEP_URL: 'http://hl7.org/fhir/StructureDefinition/maxDecimalPlaces',
  MAX_VALUE_URL: 'http://hl7.org/fhir/StructureDefinition/maxValue',
  MIN_VALUE_URL: 'http://hl7.org/fhir/StructureDefinition/minValue',
  MIN_LENGTH_URL: 'http://hl7.org/fhir/StructureDefinition/minLength',
  MAX_OCCURS_URL: 'http://hl7.org/fhir/StructureDefinition/questionnaire-maxOccurs',
  MIN_OCCURS_URL: 'http://hl7.org/fhir/StructureDefinition/questionnaire-minOccurs',
  REGEX_URL: 'http://hl7.org/fhir/StructureDefinition/regex',
  VALIDATIONTEXT_URL: 'http://ehelse.no/fhir/StructureDefinition/validationtext',
  REPEATSTEXT_URL: 'http://ehelse.no/fhir/StructureDefinition/repeatstext',
  ITEMCONTROL_URL: 'http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl',
  QUESTIONNAIRE_UNIT: 'http://hl7.org/fhir/StructureDefinition/questionnaire-unit',
  MARKDOWN_URL: 'http://hl7.org/fhir/StructureDefinition/rendering-markdown',
  AUTHENTICATION_REQUIREMENT_URL: 'http://ehelse.no/fhir/StructureDefinition/sdf-authenticationrequirement',
  CAN_BE_PERFORMED_BY_URL: 'http://ehelse.no/fhir/StructureDefinition/sdf-canbeperformedby',
  ACCESSIBILITY_TO_RESPONSE: 'http://ehelse.no/fhir/StructureDefinition/sdf-accessibilitytoresponse',
  DISCRETION: 'http://ehelse.no/fhir/StructureDefinition/sdf-discretion',
  OPTION_REFERENCE: 'http://ehelse.no/fhir/StructureDefinition/sdf-optionReference',
};
