export default {
  ENTRY_FORMAT_URL: 'http://hl7.org/fhir/StructureDefinition/entryFormat',
  STEP_URL: 'http://hl7.org/fhir/StructureDefinition/maxDecimalPlaces',
  MAX_VALUE_URL: 'http://hl7.org/fhir/StructureDefinition/maxValue',
  MIN_VALUE_URL: 'http://hl7.org/fhir/StructureDefinition/minValue',
  MIN_LENGTH_URL: 'http://hl7.org/fhir/StructureDefinition/minLength',
  MAX_OCCURS_URL: 'http://hl7.org/fhir/StructureDefinition/questionnaire-maxOccurs',
  MIN_OCCURS_URL: 'http://hl7.org/fhir/StructureDefinition/questionnaire-minOccurs',
  REGEX_URL: 'http://hl7.org/fhir/StructureDefinition/regex',
  ITEMCONTROL_URL: 'http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl',
  QUESTIONNAIRE_UNIT: 'http://hl7.org/fhir/StructureDefinition/questionnaire-unit',
  MARKDOWN_URL: 'http://hl7.org/fhir/StructureDefinition/rendering-markdown',
  QUESTIONNAIRE_HIDDEN: 'http://hl7.org/fhir/StructureDefinition/questionnaire-hidden',
  ORDINAL_VALUE: 'http://hl7.org/fhir/StructureDefinition/ordinalValue',

  VALIDATIONTEXT_URL: 'http://ehelse.no/fhir/StructureDefinition/validationtext',
  REPEATSTEXT_URL: 'http://ehelse.no/fhir/StructureDefinition/repeatstext',
  OPTION_REFERENCE: 'http://ehelse.no/fhir/StructureDefinition/sdf-optionReference',
  CALCULATED_EXPRESSION: 'http://ehelse.no/fhir/StructureDefinition/sdf-calculatedExpression',
  Copy_EXPRESSION: 'http://hl7.org/fhir/StructureDefinition/cqf-expression',
  DATE_MAX_VALUE_URL: 'http://ehelse.no/fhir/StructureDefinition/sdf-maxvalue',
  DATE_MIN_VALUE_URL: 'http://ehelse.no/fhir/StructureDefinition/sdf-minvalue',

  GUIDANCE_PARAMETER: 'http://helsenorge.no/fhir/StructureDefinition/sdf-guidanceparameter',
  GUIDANCE_ACTION: 'http://helsenorge.no/fhir/StructureDefinition/sdf-guidanceaction',
  PRESENTATION_BUTTONS: 'http://helsenorge.no/fhir/StructureDefinition/sdf-presentationbuttons',
  NAVIGATOR: 'http://helsenorge.no/fhir/StructureDefinition/sdf-questionnaire-navgiator-state',
  SUBLABEL: 'http://helsenorge.no/fhir/StructureDefinition/sdf-sublabel',

  HYPERLINK: 'http://helsenorge.no/fhir/StructureDefinition/sdf-hyperlink-target',
};
