export default {
  BOOLEAN: 'boolean',
  GROUP: 'group',
  DISPLAY: 'display',
  DECIMAL: 'decimal',
  DATE: 'date',
  DATETIME: 'dateTime',
  TIME: 'time',
  TEXT: 'text',
  STRING: 'string',
  INTEGER: 'integer',
  CHOICE: 'choice',
  OPENCHOICE: 'open-choice',
  ATTATCHMENT: 'attachment',
  QUANTITY: 'quantity',
};
