export enum ScoringItemType {
  TOTAL_SCORE = 'TOTAL_SCORE',
  SECTION_SCORE = 'SECTION_SCORE',
  QUESTION_SCORE = 'QUESTION_SCORE',
  QUESTION_FHIRPATH_SCORE = 'QUESTION_FHIRPATH_SCORE',
  NONE = 'NONE',
}
