import { Resources } from '../../src/util/resources.ts';

export const getResources = (language: string): Resources => {
  if (language === 'en-GB') {
    return {
      openChoiceOption: 'Other',
      deleteButtonText: 'Delete',
      validationSummaryHeader: 'Check that the following are filled in correctly:',
      supportedFileFormats: 'Valid file formats are jpeg, png and pdf',
      selectDefaultPlaceholder: 'Select one of the options.',
      errorAfterMaxDate: 'Date cannot be after maximum date',
      errorBeforeMinDate: 'Date cannot be before minimum date',
      oppgiVerdi: 'Select one of the options.',
      oppgiGyldigVerdi: 'Please enter a valid value',
      formCancel: 'Cancel',
      formSend: 'Submit',
      formSave: 'Show QuestionnaireResponse',
      formOptional: '(optional)',
      repeatButtonText: 'Add',
      confirmDeleteButtonText: 'Delete row',
      confirmDeleteCancelButtonText: 'Discard changes',
      confirmDeleteHeading: 'There are unsaved changes',
      confirmDeleteDescription: 'If you delete the row, your changes will be discarded.',
      ikkeBesvart: 'Not answered',
      uploadButtonText: 'Upload file',
      validationNotAllowed: 'is not allowed',
      formRequiredErrorMessage: 'This field is required',
      deleteAttachmentText: 'Delete',
      autoSuggestLoadError: 'Technical error',
      autosuggestNoSuggestions: 'No results found for "{0}". Try another word or check for spelling errors.',
      stringOverMaxLengthError: 'You have typed too many characters. Make the text shorter.',
      chooseFilesText: 'Select files',
      skipLinkText: 'Go to navigator',

      year_field_invalid: 'Enter a valid value for the year field',
      year_field_maxdate: 'The latest year you can choose is',
      year_field_mindate: 'The earliest year you can choose is',
      year_field_required: 'Year is required',
      yearmonth_field_month_placeholder: 'Choose month',
      yearmonth_field_required: 'Year and month is required',
      adresseKomponent_header: 'Who is the recipient?',
      adresseKomponent_skjemaSendesTil: 'Questionnaire will be sent to:',
      adresseKomponent_sublabel: 'You must select recipient before submitting the questionnaire.',
      adresseKomponent_velgAvdeling: 'Select department',
      adresseKomponent_velgHelseforetak: 'Select health company',
      adresseKomponent_velgHelseregion: 'Select health region',
      adresseKomponent_velgSykehus: 'Select hospital',
      adresseKomponent_velgKlinikk: 'Select clinic',
      adresseKomponent_velgSeksjon: 'Select section',
      adresseKomponent_velgSengepost: 'Select bed post',
      adresseKomponent_velgPoliklinikk: 'Select polyclinic',
      adresseKomponent_velgTjeneste: 'Select place of treatment',
      adresseKomponent_feilmelding: 'You must select a recipient.',
      adresseKomponent_loadError: 'Technical error. Could not load recipients.',
      linkOpensInNewTab: 'Opens in new tab',
      nextStep: 'Next',
      previousStep: 'Previous',
      attachmentError_minFiles: 'Add at least {0} file(s)',
      attachmentError_maxFiles: 'Maximum of {1} file(s) are allowed',
      attachmentError_minFiles_and_maxFiles: 'At least {0} file(s) and a maximum of {1} file(s) are allowed',
      attachmentError_fileSize: 'File size must be less than {0}MB',
      attachmentError_fileType: 'Allowed file types are:',
      dateError_invalid: 'Invalid date',
      timeError_hours_digits: 'The field for hours only allows 2 characters',
      timeError_minutes_digits: 'The field for minutes only allows 2 characters',
      dateError_time_invalid: 'Invalid time',
      dateFormat_ddmmyyyy: '(dd.mm.yyyy)',
      dateLabel_january: 'January',
      dateLabel_february: 'February',
      dateLabel_march: 'March',
      dateLabel_april: 'April',
      dateLabel_may: 'May',
      dateLabel_june: 'June',
      dateLabel_july: 'July',
      dateLabel_august: 'August',
      dateLabel_september: 'September',
      dateLabel_october: 'October',
      dateLabel_november: 'November',
      dateLabel_december: 'December',
      dateLabel_year: 'Year',
      dateLabel_month: 'Month',
      maxCharactersText: 'characters',
      quantity_unit_sublabel: 'Enter in',
      formAllOptional: 'All fields are optional',
      formAllRequired: 'All fields are required',
      formRequired: 'Required field',
    };
  }
  return {
    openChoiceOption: 'Annet',
    deleteButtonText: 'Slett',
    validationSummaryHeader: 'Sjekk at følgende er riktig utfylt:',
    supportedFileFormats: 'Gyldige filformater er jpeg, png og pdf',
    selectDefaultPlaceholder: 'Velg...',
    errorAfterMaxDate: 'Dato kan ikke være etter maksimum dato',
    errorBeforeMinDate: 'Dato kan ikke være før minimums dato',
    oppgiVerdi: 'Oppgi en verdi',
    oppgiGyldigVerdi: 'Oppgi en gyldig verdi',
    formCancel: 'Avbryt',
    formSend: 'Fullfør',
    formSave: 'Vis QuestionnaireResponse',
    repeatButtonText: 'Legg til',
    confirmDeleteButtonText: 'Forkast endringer',
    confirmDeleteCancelButtonText: 'Avbryt',
    confirmDeleteHeading: 'Det finnes endringer',
    confirmDeleteDescription: 'Hvis du sletter, vil du miste endringene.',
    ikkeBesvart: 'Ikke besvart',
    uploadButtonText: 'Last opp fil',
    validationNotAllowed: 'er ikke tillatt',
    formRequiredErrorMessage: 'Du må fylle ut dette feltet',
    deleteAttachmentText: 'Slett',
    autoSuggestLoadError: 'Teknisk feil',
    autosuggestNoSuggestions: 'Ingen treff på "{0}". Prøv med et annet ord eller sjekk for skrivefeil.',
    stringOverMaxLengthError: 'Du har skrevet for mange tegn. Gjør teksten kortere.',
    chooseFilesText: 'Velg filer',
    skipLinkText: 'Hopp til navigator',

    year_field_invalid: 'Du må skrive inn et gyldig årstall',
    year_field_maxdate: 'Årstall er etter det eldste tillatte år',
    year_field_mindate: 'Årstall er før det minste tillatte år',
    year_field_required: 'Årstall er påkrevd',
    yearmonth_field_month_placeholder: 'Velg måned',
    yearmonth_field_required: 'Årstall og måned er påkrevd',
    adresseKomponent_header: 'Hvem er mottaker av skjemaet?',
    adresseKomponent_skjemaSendesTil: 'Skjemaet sendes til:',
    adresseKomponent_sublabel: 'Du må velge mottaker før du sender skjemaet.',
    adresseKomponent_velgAvdeling: 'Velg avdeling',
    adresseKomponent_velgHelseforetak: 'Velg helseforetak',
    adresseKomponent_velgHelseregion: 'Velg helseregion',
    adresseKomponent_velgSykehus: 'Velg sykehus',
    adresseKomponent_velgKlinikk: 'Velg klinikk',
    adresseKomponent_velgSeksjon: 'Velg seksjon',
    adresseKomponent_velgSengepost: 'Velg sengepost',
    adresseKomponent_velgPoliklinikk: 'Velg poliklinikk',
    adresseKomponent_velgTjeneste: 'Velg behandlingssted',
    adresseKomponent_feilmelding: 'Du må velge en mottaker',
    adresseKomponent_loadError: 'Teknisk feil: kunne ikke laste liste over mottakere',
    linkOpensInNewTab: 'Åpnes i ny fane',
    nextStep: 'Neste',
    previousStep: 'Forrige',
    attachmentError_minFiles: 'Legg til minst {0} fil(er)',
    attachmentError_maxFiles: 'Maks {1} fil(er) er tillatt',
    attachmentError_minFiles_and_maxFiles: 'Minst {0} fil(er) og maks {1} fil(er) er tillatt',
    attachmentError_fileSize: 'Filstørrelse må være mindre enn {0}MB',
    attachmentError_fileType: 'Tillatte filtyper er:',
    dateError_invalid: 'Ugyldig dato',
    timeError_hours_digits: 'Felt for timer tillater kun 2 tegn',
    timeError_minutes_digits: 'Felt for minutter tillater kun 2 tegn',
    dateError_time_invalid: 'Ugyldig klokkeslett',
    dateFormat_ddmmyyyy: '(dd.mm.åååå)',
    dateLabel_january: 'Januar',
    dateLabel_february: 'Februar',
    dateLabel_march: 'Mars',
    dateLabel_april: 'April',
    dateLabel_may: 'Mai',
    dateLabel_june: 'Juni',
    dateLabel_july: 'Juli',
    dateLabel_august: 'August',
    dateLabel_september: 'September',
    dateLabel_october: 'Oktober',
    dateLabel_november: 'November',
    dateLabel_december: 'Desember',
    dateLabel_year: 'År',
    dateLabel_month: 'Måned',
    maxCharactersText: 'tegn',
    quantity_unit_sublabel: 'Oppgi i',

    alternativer_tekst: 'Alternativer',
    anonymousUploadDescription: 'Filen(e) du laster opp vil bli knyttet til skjemaet ditt og sendt til mottakeren av skjemaet.',
    anonymousUploadTitle: 'Last opp fil(er)',
    attachment_max_occurrences: 'Maksimalt antall vedlegg er nådd',
    attachment_max_occurrences_single_file: 'Maksimalt antall vedlegg er nådd',
    attachment_min_occurrences_single_file: 'Du må legge til minst ett vedlegg',
    attachmentError_fileSize_total: 'Total filstørrelse må være mindre enn {0}MB',
    attachmentError_wrong_file_type: 'Følgende filtyper er ikke tillatt:',
    autolagering_emne: 'Autolagring av skjema',
    autolagering_tekst: 'Skjemaet ditt har blitt autolagret.',
    berikingFailedOnRetrievalBody: 'Det oppstod en feil ved henting av data for beriking. Prøv igjen senere.',
    berikingFailedOnRetrievalTitle: 'Feil ved henting av data',
    confirmationActionButton: 'Fortsett',
    confirmDiscretionlagreAndSendButtonText: 'Fortsett uten å lagre',
    formOptional: 'Valgfritt',
    formAllOptional: 'Alle felt er valgfrie',
    formAllRequired: 'Alle felt må fylles ut',
    formRequired: 'Påkrevd felt',
    formRequiredInputs: 'Må fylles ut',
    formRequiredSingleCheckbox: 'Må velges',
    formRequiredMultiCheckbox: 'Velg en eller flere',
    formRequiredRadiobuttonList: 'Velg én',
  };
};
